markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown (GFM)
  auto_ids: true
  hard_wrap: true
  syntax_highlighter: rouge

collections: 
  posts:
    output: true
  projects:
    output: true
  interests:
    output: true


